# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05proxy\"&\n\x0ePredictRequest\x12\x14\n\x0cjson_request\x18\x01 \x01(\t\"(\n\x0fPredictResponse\x12\x15\n\rjson_response\x18\x01 \x01(\t2H\n\x0cProxyService\x12\x38\n\x07Predict\x12\x15.proxy.PredictRequest\x1a\x16.proxy.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=24
  _globals['_PREDICTREQUEST']._serialized_end=62
  _globals['_PREDICTRESPONSE']._serialized_start=64
  _globals['_PREDICTRESPONSE']._serialized_end=104
  _globals['_PROXYSERVICE']._serialized_start=106
  _globals['_PROXYSERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
